export interface CustomerBank {
    CustomerBankId: number,
    Name: string,
    BankCode: string,
    BankTitle: string,
    AccountNumber: string,
    RoutingCode: string,
    SwiftCode: string,
    RemitCode: string,
    Remitkey: string,
    UniqueId: string,
    RemitTyoe: string,
    BranchCode: string,
    Branch: string,
    BranchContactNumber: string,
    BranchAddress: string,
    GlCode: string,
    Active: boolean,
    CustomerTypeId: number
}