export interface SalesPerson {
    SalesPersonId: number,
    FirstName: string,
    MiddleName: string,
    LastName: string,
    Company: string,
    FullName: string,
    DOB: Date,
    PlaceOfBirth: string,
    Occupation: string,
    NIC: string,
    Gender: string,
    PhoneNumber: string,
    Remarks: string,
    ResidenceAddress: string,
    OfficeAddress: string,
    OfficeTel: string,
    ForeignAddress: string,
    Country: string,
    City: string,
    State: string,
    PostalCode: string,
    DistributorId: number
}